import java.util.Random;

public class Item59 {

    static Random rnd = new Random();
    static int random(int n){
        return Math.abs(rnd.nextInt()) % n;
    }

    public static void main(String[] args){

        int n = 2 * (Integer.MAX_VALUE/3);
        int low = 0;
        for (int i = 0; i < 1000000; i++)
            if (random(n) < n/2)
                low++;
        System.out.println(low); // will get a number close to 666,666

        // Two third of the numbers generated by the random method fall in the lower half of its range
        // This implementation from the library is flawed, but has been corrected with
        // Random.nextInt(int)
    }


}
